name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.2'

    - name: Create build directory
      run: cmake -B ${{ github.workspace }}/build -S .

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Run tests
      run: ctest -C Release
      working-directory: ${{ github.workspace }}/build/tests