name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.2'
    
    - name: Install Qt and OpenGL
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libglu1-mesa-dev freeglut3-dev

    - name: Create build directory
      run: cmake -B ${{ github.workspace }}/build -S .

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Run tests
      run: ctest -C Release
      working-directory: ${{ github.workspace }}/build/tests