name: clang-tidy-review

on:
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.19.0
        id: review
        with:
          build_dir: build
          apt_packages: "libfftw3-dev,libnetcdf-c++4-dev,libopenmpi-dev,petsc-dev,slepc-dev,liblapack-dev,libparpack2-dev,libsundials-dev,uuid-dev"

      - uses: ZedThree/clang-tidy-review/upload@v0.14.0
        id: upload-review

      - if: steps.review.outputs.total_comments > 0
        run: exit 1